### ISSUE TITLE
Hide mark in FriendlyHUD 3d mark view 

### ISSUE THREAD

**Issue by Tarch1** [Aelto/tw3-random-encounters-reworked#132]
Maybe it's not a problem and i'm just blind, to don't see the correct option, but how we can remove the bounty hounter mark?
I've see an option Markers - bounty hounting but changing it didn't work
Thank you for his great mod :)

PS: there is a chance to make it compatible with linux?

**Comment by Aelto** [comment]
Hello, there is currently no option to hide the added 3D markers from RER & FHUD. The only solution would be to remove the FHUD patch.

What do you mean making it compatible with Linux? If you are able to make the game run on linux, then the mod will work on linux as well. If you meant the various scripts i wrote then i fear it would require a good amount of time to convert them to bash. Though you may not even need them to bundle the mod, it would be a long process but perfectly doable.

**Comment by Tarch1** [comment]
OK thanks,
abot converting them, you mean the update-registry.bat and others two update for the mod itself, ot there are others somewhere else? (in windows I used only the first)

**Comment by Aelto** [comment]
Or sorry i see now, if the scripts don't work (which is probably the case since they're batch and powershell) then you should do it the manual way:
 - [video guide](https://www.youtube.com/watch?v=QBLdV3T2IKs)
 - [written guide](https://aelto.github.io/tw3-random-encounters-reworked/indepth-guide/)

The only step where you may need help is the registry step. In the video guide i display what the content of your registry should be but in the written guide i tell you to use a script. You should add the two following lines in your registry (don't copy the `+` signs, they're here to highlight the lines):
```diff
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
class CModRegistry extends CModFactory {
    protected function createMods() {
        // add mod creation calls here, like this:
        //
        // add(modCreate_<ModName>());
        // ...

        // see example dir
        //add(modCreate_ExampleMod());
        //add(modCreate_ExampleEntityMod());
        //add(modCreate_UiExampleMod());

+	// Random Encounters Reworked - https://www.nexusmods.com/witcher3/mods/5018 
+	add(modCreate_RandomEncountersReworked());
    }
}
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
```

Once you've added these lines you'll get the results you would have gotten by using the script. And i think that's the only part that has no written explanation for a manual install.

**Comment by Tarch1** [comment]
PS: when not activated properly, I've found that there is an invisible griffin (or something else) that roars around and spawn dead enemies bodies
